spring:
  application:
    name: weather-event-service
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    admin:
      auto-create: false
    weather-topic: "weather-event"

KAFKA_HOST: ${KAFKA_OUTSIDE_HOST}
KAFKA_PORT: ${KAFKA_OUTSIDE_PORT}

weather:
  generator:
    period: 10000