spring:
  application:
    name: bishop
  config:
    import: optional:file:.env[.properties]

synthetic-human:
  executor:
    thread-pool-size: 2
    queue-size: 4
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    weyland-topic: "weyland-logging-topic"
  logging:
    publisher-type: kafka

KAFKA_HOST: ${KAFKA_OUTSIDE_HOST}
KAFKA_PORT: ${KAFKA_OUTSIDE_PORT}
