services:
  consent_zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: "consent-zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_OUTSIDE_PORT}:2181
    networks:
      - sopd_sign_network

  consent_kafka:
    image: confluentinc/cp-kafka:7.9.0
    env_file:
      - .env
    container_name: "consent-kafka"
    depends_on:
      - consent_zookeeper
    restart: unless-stopped
    ports:
      - ${KAFKA_OUTSIDE_PORT}:${KAFKA_OUTSIDE_PORT}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: consent_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://consent_kafka:29092,EXTERNAL://${KAFKA_OUTSIDE_HOST}:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    networks:
      - sopd_sign_network

  consent_db_postgres:
    container_name: "consent-postgres"
    env_file:
      - .env
    image: 'postgres:16.4'
    environment:
      POSTGRES_USER: ${CONSENT_PG_USER}
      POSTGRES_PASSWORD: ${CONSENT_PG_PASSWORD}
      POSTGRES_DB: ${CONSENT_PG_DATABASE}
    ports:
      - "${CONSENT_PG_PORT}:5432"
    networks:
      - sopd_sign_network

  consent_flyway:
    container_name: "consent-flyway"
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://consent_db_postgres:5432/${CONSENT_PG_DATABASE}
      FLYWAY_USER: ${CONSENT_PG_USER}
      FLYWAY_PASSWORD: ${CONSENT_PG_PASSWORD}
    command:
      - migrate
    volumes:
      - ./src/main/resources/migrations:/flyway/sql
    image: 'flyway/flyway:11.4'
    depends_on:
      consent_db_postgres:
        condition: service_started
        restart: true
    networks:
      - sopd_sign_network

  service:
    build:
      dockerfile: Dockerfile
    container_name: "consent-service"
    env_file:
      - .env
    environment:
      PG_HOST: consent_db_postgres
      PG_PORT: 5432
      PUBLIC_KEY_FILE_PATH: keys/public/jws-public.pem
    ports:
      - "${CONSENT_SERVICE_PORT}:8080"
    volumes:
      - ./src/main/resources/keys/public:/keys/public
    depends_on:
      - consent_db_postgres
    networks:
      - sopd_sign_network

networks:
  sopd_sign_network:
    name: "sopd-network"
    driver: bridge
    external: true