create table sopd_documents (
    version int primary key generated by default as identity,
    key varchar(120),
    created_at timestamp
);
insert into sopd_documents(key, created_at) values ('sopd_document_v1.html', current_timestamp);

create table email_forms (
    version int primary key generated by default as identity,
    key varchar(120) unique,
    created_at timestamp
);
insert into email_forms(key, created_at) values ('email_form_v1.html', current_timestamp);

create table candidate_profiles (
    id int primary key generated by default as identity,
    email varchar(100) unique,
    first_name varchar(100),
    second_name varchar(100),
    third_name varchar(100),
    birthdate date,
    phone varchar(20) unique,
    created_at timestamp,
    updated_at timestamp
);

create table consents (
    id uuid primary key,
    sopd_document_version int references sopd_documents(version),
    manager_id int,
    candidate_profile_id int references candidate_profiles(id),
    status varchar(20),
    created_at timestamp,
    updated_at timestamp
);

create table documents_prime_version (
    id int primary key,
    sopd_document_prime_version int references sopd_documents(version),
    email_form_prime_version int references email_forms(version)
);
insert into documents_prime_version values (1, 1, 1);

create table sopd_request_email_messages (
    id uuid primary key,
    consent uuid references consents(id),
    status varchar(20),
    created_at timestamp
);
