services:
  weather-statistics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-statistics-service
    env_file:
      - .env
    networks:
      - weather

networks:
  weather:
    name: weather-event-network
    external: true