create table users (
    id int primary key generated by default as identity,
    email varchar(100) unique,
    password varchar(512),
    name varchar(50)
);

create table roles (
    id int primary key generated by default as identity,
    name varchar(15) unique
);
insert into roles (name) values ('ROLE_ADMIN'),
                                ('ROLE_OPERATOR'),
                                ('ROLE_CLIENT');

create table user_role (
    user_id int references users(id),
    role_id int references roles(id),
    primary key (user_id, role_id)
);

insert into users(email, password, name) values ('email1@gmail.com', 'password1', 'name1');

insert into user_role(user_id, role_id) values (1, 1),
                                               (1, 3);